# Generated by Django 4.2.4 on 2023-08-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=80)),
                ('aks1', models.CharField(max_length=80)),
                ('aks2', models.CharField(max_length=80)),
                ('aks3', models.CharField(max_length=80)),
                ('aks4', models.CharField(max_length=80)),
                ('aks5', models.CharField(max_length=80)),
                ('aks6', models.CharField(max_length=80)),
                ('aks7', models.CharField(max_length=80)),
            ],
        ),
    ]
