# Generated by Django 4.2.4 on 2023-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeb',
            name='aks1',
            field=models.ImageField(upload_to='typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks2',
            field=models.ImageField(upload_to='typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks3',
            field=models.ImageField(upload_to='typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks4',
            field=models.ImageField(upload_to='typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks5',
            field=models.ImageField(upload_to='typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks6',
            field=models.ImageField(upload_to='typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks7',
            field=models.ImageField(upload_to='typeb'),
        ),
    ]
