# Generated by Django 4.2.4 on 2023-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_typeb_aks1_alter_typeb_aks2_alter_typeb_aks3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeb',
            name='aks1',
            field=models.ImageField(upload_to='media/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks2',
            field=models.ImageField(upload_to='media/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks3',
            field=models.ImageField(upload_to='media/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks4',
            field=models.ImageField(upload_to='media/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks5',
            field=models.ImageField(upload_to='media/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks6',
            field=models.ImageField(upload_to='media/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks7',
            field=models.ImageField(upload_to='media/typeb'),
        ),
    ]
