# Generated by Django 4.2.4 on 2023-08-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_typeb_aks1_alter_typeb_aks2_alter_typeb_aks3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='catb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esm', models.CharField(max_length=80)),
                ('aks1', models.ImageField(upload_to='Home/typeb')),
                ('idcat', models.CharField(max_length=80)),
            ],
        ),
    ]
