# Generated by Django 4.2.4 on 2023-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_catb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catb',
            name='idcat',
            field=models.IntegerField(),
        ),
    ]
