# Generated by Django 4.2.4 on 2023-08-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_catb_idcat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catb',
        ),
    ]
