# Generated by Django 4.2.4 on 2023-08-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_delete_catb'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeb',
            name='aks8',
            field=models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks1',
            field=models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks2',
            field=models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks3',
            field=models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks4',
            field=models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks5',
            field=models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks6',
            field=models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb'),
        ),
        migrations.AlterField(
            model_name='typeb',
            name='aks7',
            field=models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb'),
        ),
    ]
