# Generated by Django 4.2.4 on 2023-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_typeb_aks8_alter_typeb_aks1_alter_typeb_aks2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tamas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phonen', models.CharField(max_length=80)),
                ('massage', models.TextField()),
            ],
        ),
    ]
