# Generated by Django 4.2.4 on 2023-09-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_tamas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamas',
            old_name='phonen',
            new_name='phone',
        ),
    ]
