# Generated by Django 4.2.4 on 2023-09-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_rename_phonen_tamas_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namebook', models.CharField(max_length=80)),
                ('aks1', models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb')),
                ('aks2', models.ImageField(default='Home/image/cat6.jpg', null=True, upload_to='Home/typeb')),
                ('nevisande', models.CharField(max_length=80)),
                ('genre', models.CharField(max_length=80)),
                ('kholase', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='typeb',
            name='aks2',
        ),
        migrations.RemoveField(
            model_name='typeb',
            name='aks3',
        ),
        migrations.RemoveField(
            model_name='typeb',
            name='aks4',
        ),
        migrations.RemoveField(
            model_name='typeb',
            name='aks5',
        ),
        migrations.RemoveField(
            model_name='typeb',
            name='aks6',
        ),
        migrations.RemoveField(
            model_name='typeb',
            name='aks7',
        ),
        migrations.RemoveField(
            model_name='typeb',
            name='aks8',
        ),
    ]
